= Parameterized onehot encoder in SystemVerilog
MIURA Katsuyoshi <miura.katsuyoshi@gmail.com>
v1.0, 2021-04-11
:toc:
:xrefstyle: short
:imagesdir: Images
:homepage: https://github.com/miura-katsuyoshi/onehot

== Description

Parameterized one-hot code encoder in SystemVerilog.

This is a binary to one-hot-code encoder implemented in SystemVerilog.  This circuit is combinational.  The bit width of the input _bin_ can be spefified by the parameter _WIDTH_.  The bit width of the output _onehot_ is 2^_WIDTH_^.  When _bin_ == 0, the least significant bit of _onehot_ becomes 1 and the others become 0.  When _bin_ == 2^_WIDTH_^-1, the most significant bit of _onehot_ becomes 1 and the others become 0.

== Input/Output

[cols="1,1,1,1,3"]
|===
|Name |Direction |Width |Polarity |Description

|bin |input |WIDTH |- |binary code
|onehot |output |2^_WIDTH_^ |positive |onehot code
|===

== Parameter

[cols="1,1,1,1,3"]
|===
|Name |Type |Width |Default value |Description

|WIDTH | int | 32 |4 |The bit width of _bin_.
|===

== Timing-chart

A timing-chart of 3-bit onehot encoder is shown in <<fig:timing_chart>>.

[[fig:timing_chart]]
.A timing-chart of 3-bit onehot encoder.
image::timing_chart.svg[]

== Instantiation

    onehot #(
        .WIDTH(4)
    )
    onehot(
        .bin(bin_signal),
        .onehot(onehot_wire)
    );

== Test

A testbench based on https://vunit.github.io/[VUnit] is included in this repository.  Execute the script _run.py_ with python interpreter.  How to run the script is depending on your system.

 $ ./run.py
 $ python run.py
 $ python3 run.py
 $ py run.py
